spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/mc_cost
    username: root
    password: 1234
  jpa:
    database:
    show-sql: true
    hibernate:
      ddl-auto: update

  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:templates/
    suffix: .html